name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.1.0
        with:
          USERNAME: ${{ github.repository_owner }}
          COMMIT_MSG: "feat: update 3D contrib"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
